"use client";

import { createContext, useContext, useMemo, useState } from "react";

export type Language = "nl" | "en";

const STORAGE_KEY = "snelvink-language";

export const translations = {
  nl: {
    // Core HACCP terms
    koeling: "Koeling",
    kerntemperatuur: "Kerntemperatuur",
    schoonmaak: "Schoonmaak",
    ontvangst: "Ontvangst",
    goedgekeurd: "Goedgekeurd",
    afgekeurd: "Afgekeurd",
    // Shared labels
    languageSectionTitle: "Taal / Language",
    languageSectionSubtitle: "Kies je app-taal",
    koelingOne: "Koeling 1",
    clickToEditTemperature: "Klik op het getal om handmatig in te voeren",
    manualTemperatureInput: "Temperatuur handmatig invoeren",
    currentTemperatureAria: "Huidige temperatuur {temp}, tik om handmatig in te voeren",
    increaseOneDegree: "Eén graad hoger",
    increaseTenthDegree: "Nul komma één hoger",
    decreaseOneDegree: "Eén graad lager",
    decreaseTenthDegree: "Nul komma één lager",
    registered: "Geregistreerd!",
    photoAdded: "Foto toegevoegd",
    takePhotoOptional: "Maak een foto (Optioneel)",
    photoPreviewAlt: "Voorbeeld van toegevoegde foto",
    saving: "Laden...",
    save: "Opslaan",
    basicPlanPhotoMessage:
      "Alleen beschikbaar voor Basic-abonnement. Upgrade om foto's toe te voegen als bewijs voor de NVWA.",
    close: "Sluiten",
    loadingApp: "SnelVink laden...",
    brandTagline: "Meten · Vinken · Weten",
    loadingReminders: "Herinneringen laden...",
    menuOpen: "Menu openen",
    menuClose: "Menu sluiten",
    mainNavigation: "Hoofdnavigatie",
    comingSoon: "Binnenkort",
    navRegistreren: "Registreren",
    navTaken: "Taken",
    navGeschiedenis: "Geschiedenis",
    navPersoneel: "Personeelsbeheer",
    navProfiel: "Mijn profiel",
    navRestaurant: "Mijn restaurant",
    navInstellingen: "Instellingen",
    registrerenTitle: "Registreren",
    newRegistration: "Nieuwe registratie",
    newRegistrationHint:
      "Tik op de knop hierboven om een nieuwe registratie te starten.",
    chooseModule: "Kies een module",
    reminders: "Herinneringen",
    today: "Vandaag",
    tomorrow: "Morgen",
    thisWeek: "Deze week",
    allPlanning: "Alle planning",
    todayAllDone: "Vandaag zijn alle taken voltooid.",
    noTasksTomorrow: "Morgen staan er geen taken gepland.",
    noTasksThisWeek: "Deze week staan er geen taken gepland.",
    remindersLoadFailed: "Herinneringen laden mislukt.",
    recordsLoadFailed: "Registraties laden mislukt.",
    filterByType: "Filter op type",
    filterRecords: "Filter registraties",
    resetFilters: "Filters wissen",
    noRegistrationsForFilter: "Geen registraties met deze filters.",
    allTasks: "Alle taken",
    all: "Alle",
    incompleteTasks: "Onvoltooide taken",
    incompleteTasksTitle: "Onvoltooide taken",
    incompleteTasksIntro:
      "Geplande taken uit het verleden waarvoor geen registratie is aangemaakt.",
    viewIncompleteTasks: "Bekijk onvoltooide taken",
    noIncompleteTasks: "Geen onvoltooide taken in deze periode.",
    noIncompleteTasksForFilter: "Geen onvoltooide taken met deze filters.",
    selectAll: "Alles selecteren",
    deselectAll: "Selectie wissen",
    selectedCount: "{count} geselecteerd",
    markAsCompleted: "Markeer als voltooid",
    marking: "Bezig met markeren...",
    markCompletedWarningTitle: "Let op",
    markCompletedWarning:
      "Deze taken worden uit de lijst van onvoltooide taken verwijderd, maar er wordt GEEN registratie aangemaakt en ze verschijnen NIET bij de voltooide registraties. Wil je de taak alsnog uitvoeren? Voeg dan handmatig een nieuwe registratie toe via Registreren.",
    confirm: "Bevestigen",
    markedAsCompleted: "{count} taken gemarkeerd als voltooid.",
    markCompletedFailed: "Markeren mislukt.",
    incompleteTasksLoadFailed: "Onvoltooide taken laden mislukt.",
    last30DaysLabel: "Laatste 30 dagen",
    previousMonth: "Vorige maand",
    nextMonth: "Volgende maand",
    chooseMonth: "Maand kiezen",
    chooseYear: "Jaar kiezen",
    noPlannedTasksOnDay: "Geen geplande taken op deze dag.",
    months: "Januari|Februari|Maart|April|Mei|Juni|Juli|Augustus|September|Oktober|November|December",
    weekdaysShort: "Ma|Di|Wo|Do|Vr|Za|Zo",
    weekdaysFull: "Maandag|Dinsdag|Woensdag|Donderdag|Vrijdag|Zaterdag|Zondag",
    restaurantManageIntro: "Beheer je restaurantgegevens en instellingen.",
    openingHours: "Openingstijden",
    openingHoursManage: "Openingstijden en sluitingsdagen beheren",
    ownerOnlyRestaurantSettings:
      "Alleen de eigenaar kan restaurantinstellingen aanpassen.",
    backToRestaurant: "Terug naar restaurant",
    openingHoursIntro:
      "Stel hier de openingstijden in. Dagelijkse taken worden niet gepland op dagen waarop het restaurant gesloten is.",
    closedDays: "Sluitingsdagen",
    noClosedDays: "Geen extra sluitingsdagen ingesteld.",
    closedDayAdd: "Sluitingsdag toevoegen",
    closedDayRemove: "{date} verwijderen",
    from: "Van",
    to: "Tot",
    open: "Open",
    closed: "Gesloten",
    restaurantSettingsSaved: "Restaurantinstellingen opgeslagen.",
    saveFailed: "Opslaan mislukt.",
    frequency: "Frequentie",
    frequencyIntro:
      "Als deze taak niet periodiek is, klik dan direct op Nieuwe registratie in Registreren.",
    notPeriodic: "Niet periodiek",
    daily: "Dagelijks",
    weekly: "Wekelijks",
    monthly: "Maandelijks",
    yearly: "Jaarlijks",
    custom: "Aangepast",
    assignTimes: "Tijdstippen toewijzen?",
    yes: "Ja",
    no: "Nee",
    registrationTime: "{ordinal} registratietijd",
    registrationDate: "{ordinal} registratiedatum",
    optional: "Optioneel",
    addReminder: "Herinnering toevoegen",
    removeReminder: "Herinnering verwijderen",
    add: "Toevoegen",
    remove: "Verwijderen",
    move: "Verplaatsen",
    edit: "Wijzigen",
    done: "Klaar",
    ordinal1: "Eerste",
    ordinal2: "Tweede",
    ordinal3: "Derde",
    ordinal4: "Vierde",
    ordinal5: "Vijfde",
    ordinalN: "{n}e",
    theme: "Thema",
    changeTheme: "Thema wijzigen",
    staffIntro: "Beheer je teamleden en hun toegangsrechten",
    profileIntro: "Bekijk en bewerk je persoonlijke gegevens",
    deletedMessage: '"{name}" verwijderd',
    undo: "Ongedaan",
    settingsTitle: "Instellingen",
    restaurant: "Restaurant",
    refresh: "Vernieuwen",
    subscription: "Abonnement",
    manageSubscription: "Beheer abonnement",
    viewRestaurantSubscription: "Bekijk het abonnement van dit restaurant",
    inviteCode: "Koppelcode",
    loading: "Laden...",
    inviteCodeUnavailableTitle: "Nog geen koppelcode beschikbaar",
    inviteCodeUpgradeMessage:
      "Upgrade je abonnement naar Basic of Pro om medewerkers te kunnen koppelen en de koppelcode te ontgrendelen.",
    inviteCodeShareMessage: "Deel deze code met je werknemers om ze te koppelen.",
    inviteCodeUnavailable: "Geen koppelcode beschikbaar.",
    staff: "Personeel",
    linkedStaffIntro: "Gekoppelde medewerkers van dit restaurant.",
    noLinkedStaff: "Nog geen personeel gekoppeld.",
    unnamed: "Naamloos",
    unknownEmail: "Onbekend e-mailadres",
    busy: "Bezig...",
    delete: "Verwijderen",
    signingOut: "Uitloggen...",
    signOut: "Uitloggen",
    temperatureRegistration: "Temperatuur Registratie",
    cleaningRegistration: "Schoonmaak Registratie",
    dateTime: "Datum/Tijd",
    equipment: "Apparaat",
    temperature: "Temperatuur",
    task: "Taak",
    status: "Status",
    completed: "Voltooid",
    noTasksChecked: "Geen taken aangevinkt",
    planStatusActive: "Actief",
    planStatusTrialing: "Proefperiode",
    planStatusPastDue: "Betaling vereist",
    planStatusCanceled: "Opgezegd",
    planStatusIncomplete: "Onvoltooid",
    planStatusUnpaid: "Niet betaald",
    planStatusPaused: "Gepauzeerd",
    moduleEdit: "Module bewerken",
    newModule: "Nieuwe module",
    standard: "Standaard",
    alreadyAdded: "Toegevoegd",
    moduleAlreadyAdded: "Dit onderdeel is al toegevoegd",
    customModuleNameRequired: "Vul een naam voor het onderdeel in.",
    noRestaurantLinked: "Geen restaurant gekoppeld aan je account.",
    customModuleSaveFailed: "Opslaan mislukt: {message}",
    unexpectedError: "Onverwachte fout: {message}",
    unexpectedErrorRetry: "Onverwachte fout. Probeer opnieuw.",
    moduleName: "Naam onderdeel",
    moduleNamePlaceholder: "Bijv. Kerntemperatuur soep",
    chooseIcon: "Kies een icoon",
    moduleType: "Type onderdeel",
    moduleTypeNumber: "Getal/Temperatuur",
    moduleTypeBoolean: "Ja/Nee",
    moduleTypeList: "Lijst",
    customModuleHelp:
      "Na het aanmaken kun je items toevoegen in het beheerscherm.",
    savingChanges: "Wijzigingen opslaan",
    cancel: "Annuleren",
    understood: "Begrepen",
    confirmEmail: "Bevestig je e-mailadres",
    enterOtpCode:
      "Voer de 6-cijferige code uit je e-mail in om verder te gaan.",
    oneTimeCode: "Eenmalige code",
    enterSixDigitCode: "Voer de 6-cijferige code in.",
    checking: "Controleren…",
    checkCode: "Code controleren",
    latest30Days: "Laatste 30 dagen",
    generateNvwaReport: "Genereer NVWA Rapport",
    noRegistrationsLast30Days: "Geen registraties in de afgelopen 30 dagen.",
    noRegistrationsFound: "Geen registraties gevonden.",
    time: "Tijd",
    valueStatus: "Waarde/Status",
    remarks: "Opmerkingen",
    details: "Details",
    overLimit: "Boven limiet",
    correctiveAction: "Corrigerende maatregel",
    noRemarks: "Geen opmerkingen.",
    photos: "Foto's",
    photoAlt: "Foto {number} bij registratie",
    freeHistoryLimit: "Gratis versie toont maximaal 30 dagen historie.",
    selectedReasons: "Geselecteerde redenen ({count})",
    unknownEquipment: "Onbekend apparaat",
    unknownItem: "Onbekend item",
    unknown: "Onbekend",
    unknownGroup: "Onbekende groep",
    noItemsChecked: "Geen items aangevinkt",
    unknownDate: "Onbekende datum",
    yesterday: "Gisteren",
    haccpLogbookTitle: "HACCP Logboek - SnelVink",
    reportUpgradeMessage:
      "Alleen beschikbaar voor Basic-abonnement. Upgrade om het NVWA-rapport te genereren en te printen.",
    back: "Terug",
    notSignedIn: "Niet ingelogd. Meld je opnieuw aan.",
    checkoutStartFailed: "Kon Stripe Checkout niet starten.",
    portalOpenFailed: "Kon Customer Portal niet openen.",
    paymentSuccess:
      "Betaling geslaagd - je abonnement wordt binnen enkele seconden bijgewerkt.",
    paymentCanceled: "Betaling geannuleerd. Je plan is niet gewijzigd.",
    plans: "Plannen",
    choosePlan: "Kies het plan dat past bij jouw keuken.",
    currentPlan: "Huidig plan",
    currentPeriodEnds: "Huidige periode loopt tot {date}.",
    opening: "Openen...",
    ownerOnlySubscription:
      "Alleen de eigenaar kan het abonnement wijzigen. Vraag je baas om te upgraden.",
    invoicesStripe:
      "Facturen en betaalmethoden worden beheerd via Stripe. Je kunt je abonnement op elk moment opzeggen.",
    free: "Gratis",
    perMonth: "€ {price},- / maand",
    ownerOnly: "Alleen eigenaar",
    upToStaff: "Tot {count} medewerkers",
    upgradeTo: "Upgraden naar {plan}",
    planFreeTagline: "Voor eenmansrestaurants",
    planBasicTagline: "Voor een gemiddelde zaak",
    planProTagline: "Voor grote keukens & ketens",
    planFreeFeature1: "Alleen eigenaar, geen medewerkers",
    planFreeFeature2: "Basis HACCP-registraties",
    planFreeFeature3: "Historie laatste 30 dagen",
    planFreeFeature4: "Geen foto-bijlagen",
    planBasicFeature1: "Tot 10 medewerkers",
    planBasicFeature2: "Volledige HACCP-historie",
    planBasicFeature3: "Foto-bewijs bij registraties",
    planBasicFeature4: "NVWA PDF-rapport genereren",
    planProFeature1: "Tot 50 medewerkers",
    planProFeature2: "Alles uit Basic",
    planProFeature3: "Prioriteit-ondersteuning",
    planProFeature4: "Exporteren naar CSV (binnenkort)",
    verifyEmailMissing: "Geen e-mailadres gevonden op dit account.",
    verifyEmailSendFailed:
      "Kon geen e-mail versturen. Controleer SMTP in Supabase of probeer later opnieuw.",
    verifyEmailSent:
      "Bevestigingsmail verstuurd. Open de link in je inbox om je e-mailadres te verifiëren.",
    retryError: "Er ging iets mis. Probeer het opnieuw.",
    emailNotVerified:
      "E-mailadres nog niet geverifieerd. Bevestig je account om je gegevens veilig te stellen.",
    sending: "Versturen...",
    verifyNow: "Nu verifiëren",
    itemOne: "Item 1",
    customModuleDefaultName: "Aangepast onderdeel",
    moduleNotFound: "Onderdeel niet gevonden.",
    moduleUnavailable:
      "Dit onderdeel bestaat niet meer of is niet beschikbaar.",
    itemNotFound: "Item niet gevonden.",
    productNotFound: "Product niet gevonden.",
    equipmentNotFound: "Apparaat niet gevonden.",
    locationNotFound: "Locatie niet gevonden.",
    fillName: "Vul een naam in.",
    addFailed: "Toevoegen mislukt.",
    deleteFailed: "Verwijderen mislukt.",
    renameFailed: "Hernoemen mislukt.",
    photoUploadFailed: "Foto upload mislukt. Probeer opnieuw.",
    loadLocationsFailed: "Locaties laden mislukt. Probeer opnieuw.",
    loadProductsFailed: "Producten laden mislukt. Probeer opnieuw.",
    locationAddFailed: "Locatie toevoegen mislukt.",
    productAddFailed: "Product toevoegen mislukt.",
    equipmentAddFailed: "Apparaat toevoegen mislukt.",
    taskAddFailed: "Taak toevoegen mislukt.",
    standardTasksCreateFailed: "Standaard taken aanmaken mislukt.",
    confirmDeleteHistoryKept: '"{name}" verwijderen? De historie blijft bewaard.',
    confirmDeleteLocation:
      '"{name}" verwijderen? Alle taken in deze locatie worden ook verwijderd.',
    confirmDelete: '"{name}" verwijderen?',
    editNamePrompt: "Nieuwe naam",
    editTaskNamePrompt: "Nieuwe naam voor de taak",
    editModuleTitle: "{module} - Bewerken",
    editProduct: "Product bewerken",
    editLocation: "Locatie bewerken",
    editItem: "Item bewerken",
    equipmentName: "Naam apparaat",
    productName: "Productnaam",
    locationName: "Locatienaam",
    name: "Naam",
    setDefaultValue: "Standaardwaarde instellen",
    defaultValueStartsAt:
      "Bij elke nieuwe registratie start de waarde op {value} {unit}.",
    defaultValueUsesLast:
      "Bij elke nieuwe registratie start de waarde op de laatst opgeslagen meting.",
    defaultValueUsesThis:
      "Bij elke nieuwe registratie start de waarde op deze standaardwaarde.",
    defaultValueUsesLastMeasurement:
      "Bij elke nieuwe registratie start de waarde op de laatste meting.",
    defaultValue: "Standaardwaarde",
    limitTemperature: "Limiet temperatuur",
    limitTemperatureHelp:
      "Boven deze temperatuur moet een corrigerende maatregel worden ingevuld.",
    limit: "Limiet",
    limitValue: "Limietwaarde",
    limitValueHelp:
      "Boven deze waarde moet een corrigerende maatregel worden ingevuld.",
    range: "Bereik",
    rangeValueHelp:
      "Stel een minimum en/of maximum in. Buiten dit bereik wordt de waarde als afwijking gezien.",
    minimumValue: "Minimum",
    maximumValue: "Maximum",
    rangeInvalid: "Minimumwaarde mag niet groter zijn dan maximumwaarde.",
    requireCorrectionOnReject:
      "Als afgekeurd is gekozen: corrigerende maatregel verplicht",
    requireCorrectionOutOfRange:
      "Als waarde buiten bereik valt: corrigerende maatregel verplicht",
    stepSize: "Stapgrootte",
    stepSizeHelp:
      "Bij registreren is dit de grootte van de stap voor de +/- knoppen.",
    unit: "Eenheid",
    unitPlaceholder: "bv. °C, kg, %",
    reasonsPerStatus: "Redenen per status",
    acceptReasonsTitle: "Redenen voor goedkeuring",
    rejectReasonsTitle: "Redenen voor afkeuring",
    acceptReasonsHelp:
      "Kies de mogelijke redenen die medewerkers kunnen selecteren bij goedkeuring.",
    rejectReasonsHelp:
      "Kies de mogelijke redenen die medewerkers kunnen selecteren bij afkeuring.",
    defaultLabel: "Standaard",
    newReasonPlaceholder: "Nieuwe reden...",
    addReason: "Reden toevoegen",
    other: "Anders",
    describeOptional: "Beschrijf (optioneel)",
    noReasonsConfigured: "Geen redenen geconfigureerd voor dit product.",
    reasonSelected: "{count} reden geselecteerd",
    reasonsSelected: "{count} redenen geselecteerd",
    product: "Product",
    item: "Item",
    group: "Groep",
    groups: "Groepen",
    location: "Locatie",
    locations: "Locaties",
    items: "Items",
    cleaningTasks: "Schoonmaaktaken",
    chooseLocation: "Kies een {name}",
    addLocation: "{name} toevoegen",
    nameOfLocation: "Naam van de {name}",
    addProduct: "{name} toevoegen",
    nameOfProduct: "Naam van het {name}",
    addTask: "Taak toevoegen",
    taskNamePlaceholder: "Naam van de taak",
    addItem: "Item toevoegen",
    itemNamePlaceholder: "Naam van het item",
    loadingLocations: "Locaties laden...",
    loadingProducts: "Producten laden...",
    loadingTasks: "Taken laden...",
    loadingEquipment: "Apparaten laden...",
    dateTimeLabel: "Datum & tijd",
    receivedDateTimeLabel: "Datum & tijd van ontvangst",
    measurementDateTimeLabel: "Datum & tijd van meting",
    rating: "Beoordeling",
    completedCount: "{done}/{total} voltooid",
    noteOptional: "Opmerking (optioneel)",
    notePlaceholder: "Voeg een opmerking toe...",
    photosOptional: "Foto's (optioneel)",
    maxPhotos: "Maximaal {count} foto's",
    addPhotoProgress: "Foto toevoegen ({current}/{max})",
    pickPhoto: "Foto maken of kiezen (max {count})",
    removePhoto: "Foto {number} verwijderen",
    selectAtLeastOneTask: "Vink minstens één taak aan om op te slaan.",
    holdButtonHint:
      "Houd een knop ingedrukt om snel aan te passen. Tik op het getal om handmatig in te voeren.",
    increaseOneDegreeFast:
      "Eén graad hoger (houd ingedrukt voor sneller)",
    increaseTenthDegreeFast:
      "0,1 graad hoger (houd ingedrukt voor sneller)",
    decreaseOneDegreeFast:
      "Eén graad lager (houd ingedrukt voor sneller)",
    decreaseTenthDegreeFast:
      "0,1 graad lager (houd ingedrukt voor sneller)",
    increaseStepFast:
      "{step} {unit} hoger (houd ingedrukt voor sneller)",
    decreaseStepFast:
      "{step} {unit} lager (houd ingedrukt voor sneller)",
    limitLabel: "Limiet: {value} {unit}",
    valueOverLimit: "Waarde boven limiet ({value} {unit})",
    correctiveActionRequiredHelp:
      "Vul een corrigerende maatregel in om door te gaan.",
    correctiveActionPlaceholder:
      "Bijv. Koeling op stand 4 gezet, deur gecontroleerd...",
    correctiveActionRequired:
      "Verplicht: vul een corrigerende maatregel in.",
    loginTitle: "Aanmelden",
    registerTitle: "Registreren",
    emailAddress: "E-mailadres",
    password: "Wachtwoord",
    loginFailedCheck: "Inloggen mislukt. Controleer je gegevens.",
    loginFailedRetry: "Inloggen mislukt. Probeer het opnieuw.",
    resendConfirmationFailed:
      "Kon geen nieuwe bevestigingsmail versturen. Probeer het later opnieuw.",
    unconfirmedEmailMessage:
      "Je e-mailadres is nog niet bevestigd. Controleer je inbox en je spam-/reclamemap voor de bevestigingsmail naar {email}.",
    resendConfirmation: "Bevestigingsmail opnieuw versturen",
    sent: "Verzonden",
    newConfirmationSent:
      "Nieuwe bevestigingsmail verstuurd. Vergeet je spam-map niet.",
    working: "Bezig...",
    accountType: "Accounttype",
    chooseAccountType: "Kies je accounttype",
    owner: "Eigenaar",
    employee: "Personeel",
    restaurantName: "Restaurantnaam",
    inviteCodeLabel: "Uitnodigingscode",
    inviteCodePlaceholder: "Bijv. 123456",
    inviteCodeHelp: "Vraag deze 6-cijferige code aan je werkgever.",
    fillFullName: "Vul je naam in.",
    fillRestaurantName: "Vul de restaurantnaam in.",
    invalidInviteCode: "Vul een geldige 6-cijferige uitnodigingscode in.",
    staffLimitReached:
      "Het restaurant heeft het maximale aantal medewerkers bereikt. Vraag je werkgever om zijn abonnement te upgraden.",
    inviteCodeInvalid:
      "De uitnodigingscode klopt niet. Vraag je werkgever om de juiste 6-cijferige code.",
    registerFailed: "Registreren mislukt.",
    registerFailedRetry: "Registreren mislukt. Probeer opnieuw.",
    createAccount: "Account aanmaken",
    noAccount: "Nog geen account?",
    alreadyHaveAccount: "Al een account?",
    emailAlreadyRegistered:
      "Dit e-mailadres is al geregistreerd. Log in of klik hieronder op 'Wachtwoord vergeten?'.",
    confirmationMailSent:
      "We hebben een bevestigingsmail naar {email} gestuurd. Controleer je inbox en je spam-/reclamemap. Klik op de link om je account te activeren en log daarna in.",
    scheduleAtLeastOneReminder: "Voeg minimaal één herinnering toe.",
    scheduleReminderDateTime:
      "Vul voor elke herinnering een datum en tijd in.",
    scheduleMinFrequency: "Kies een frequentie van minimaal 1.",
    scheduleDailyTimes: "Vul voor elke dagelijkse registratie een tijd in.",
    scheduleWeeklyDays:
      "Kies {count} dag(en) voor deze wekelijkse taak.",
    scheduleMonthlyDays:
      "Kies {count} dag(en) voor deze maandelijkse taak.",
    scheduleYearlyDates:
      "Kies {count} datum(s) voor deze jaarlijkse taak.",
    manageItems: "Beheer je items en instellingen",
    selectToRecord: "Selecteer een item om te registreren",
    lastValue: "Laatste waarde",
  },
  en: {
    // Core HACCP terms
    koeling: "Cooling",
    kerntemperatuur: "Core temperature",
    schoonmaak: "Cleaning",
    ontvangst: "Receiving",
    goedgekeurd: "Approved",
    afgekeurd: "Rejected",
    // Shared labels
    languageSectionTitle: "Taal / Language",
    languageSectionSubtitle: "Choose your app language",
    koelingOne: "Cooling 1",
    clickToEditTemperature: "Tap the number to enter manually",
    manualTemperatureInput: "Enter temperature manually",
    currentTemperatureAria: "Current temperature {temp}, tap to enter manually",
    increaseOneDegree: "Increase by one degree",
    increaseTenthDegree: "Increase by 0.1 degree",
    decreaseOneDegree: "Decrease by one degree",
    decreaseTenthDegree: "Decrease by 0.1 degree",
    registered: "Saved!",
    photoAdded: "Photo added",
    takePhotoOptional: "Take a photo (Optional)",
    photoPreviewAlt: "Preview of selected photo",
    saving: "Saving...",
    save: "Save",
    basicPlanPhotoMessage:
      "Only available on the Basic plan. Upgrade to add photos as evidence for the NVWA.",
    close: "Close",
    loadingApp: "Loading SnelVink...",
    brandTagline: "Measure · Tick · Know",
    loadingReminders: "Loading reminders...",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    mainNavigation: "Main navigation",
    comingSoon: "Coming soon",
    navRegistreren: "Register",
    navTaken: "Tasks",
    navGeschiedenis: "History",
    navPersoneel: "Staff management",
    navProfiel: "My profile",
    navRestaurant: "My restaurant",
    navInstellingen: "Settings",
    registrerenTitle: "Register",
    newRegistration: "New registration",
    newRegistrationHint: "Tap the button above to start a new registration.",
    chooseModule: "Choose a module",
    reminders: "Reminders",
    today: "Today",
    tomorrow: "Tomorrow",
    thisWeek: "This week",
    allPlanning: "All planning",
    todayAllDone: "All tasks for today are complete.",
    noTasksTomorrow: "No tasks are planned for tomorrow.",
    noTasksThisWeek: "No tasks are planned for this week.",
    remindersLoadFailed: "Failed to load reminders.",
    recordsLoadFailed: "Failed to load registrations.",
    filterByType: "Filter by type",
    filterRecords: "Filter records",
    resetFilters: "Reset filters",
    noRegistrationsForFilter: "No registrations match these filters.",
    allTasks: "All tasks",
    all: "All",
    incompleteTasks: "Incomplete tasks",
    incompleteTasksTitle: "Incomplete tasks",
    incompleteTasksIntro:
      "Planned tasks from the past for which no registration was created.",
    viewIncompleteTasks: "View incomplete tasks",
    noIncompleteTasks: "No incomplete tasks in this period.",
    noIncompleteTasksForFilter: "No incomplete tasks match these filters.",
    selectAll: "Select all",
    deselectAll: "Clear selection",
    selectedCount: "{count} selected",
    markAsCompleted: "Mark as completed",
    marking: "Marking...",
    markCompletedWarningTitle: "Heads up",
    markCompletedWarning:
      "These tasks will be removed from the incomplete list, but NO registration will be created and they will NOT appear in completed records. To actually fulfil the task, add a new registration manually via Register.",
    confirm: "Confirm",
    markedAsCompleted: "{count} tasks marked as completed.",
    markCompletedFailed: "Failed to mark tasks.",
    incompleteTasksLoadFailed: "Failed to load incomplete tasks.",
    last30DaysLabel: "Last 30 days",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    chooseMonth: "Choose month",
    chooseYear: "Choose year",
    noPlannedTasksOnDay: "No tasks are planned for this day.",
    months: "January|February|March|April|May|June|July|August|September|October|November|December",
    weekdaysShort: "Mon|Tue|Wed|Thu|Fri|Sat|Sun",
    weekdaysFull: "Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday",
    restaurantManageIntro: "Manage your restaurant details and settings.",
    openingHours: "Opening hours",
    openingHoursManage: "Manage opening hours and closed days",
    ownerOnlyRestaurantSettings: "Only the owner can change restaurant settings.",
    backToRestaurant: "Back to restaurant",
    openingHoursIntro:
      "Set the opening hours here. Daily tasks are not planned on days when the restaurant is closed.",
    closedDays: "Closed days",
    noClosedDays: "No extra closed days have been set.",
    closedDayAdd: "Add closed day",
    closedDayRemove: "Remove {date}",
    from: "From",
    to: "To",
    open: "Open",
    closed: "Closed",
    restaurantSettingsSaved: "Restaurant settings saved.",
    saveFailed: "Save failed.",
    frequency: "Frequency",
    frequencyIntro:
      "If this task is not recurring, use New registration directly in Register.",
    notPeriodic: "Not recurring",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    custom: "Custom",
    assignTimes: "Assign times?",
    yes: "Yes",
    no: "No",
    registrationTime: "{ordinal} registration time",
    registrationDate: "{ordinal} registration date",
    optional: "Optional",
    addReminder: "Add reminder",
    removeReminder: "Remove reminder",
    add: "Add",
    remove: "Remove",
    move: "Move",
    edit: "Edit",
    done: "Done",
    ordinal1: "First",
    ordinal2: "Second",
    ordinal3: "Third",
    ordinal4: "Fourth",
    ordinal5: "Fifth",
    ordinalN: "{n}th",
    theme: "Theme",
    changeTheme: "Change theme",
    staffIntro: "Manage your team members and access rights",
    profileIntro: "View and edit your personal details",
    deletedMessage: '"{name}" deleted',
    undo: "Undo",
    settingsTitle: "Settings",
    restaurant: "Restaurant",
    refresh: "Refresh",
    subscription: "Subscription",
    manageSubscription: "Manage subscription",
    viewRestaurantSubscription: "View this restaurant's subscription",
    inviteCode: "Invite code",
    loading: "Loading...",
    inviteCodeUnavailableTitle: "No invite code available yet",
    inviteCodeUpgradeMessage:
      "Upgrade your subscription to Basic or Pro to link staff members and unlock the invite code.",
    inviteCodeShareMessage: "Share this code with your employees to link them.",
    inviteCodeUnavailable: "No invite code available.",
    staff: "Staff",
    linkedStaffIntro: "Linked staff members for this restaurant.",
    noLinkedStaff: "No staff linked yet.",
    unnamed: "Unnamed",
    unknownEmail: "Unknown email address",
    busy: "Working...",
    delete: "Delete",
    signingOut: "Signing out...",
    signOut: "Sign out",
    temperatureRegistration: "Temperature Registration",
    cleaningRegistration: "Cleaning Registration",
    dateTime: "Date/Time",
    equipment: "Equipment",
    temperature: "Temperature",
    task: "Task",
    status: "Status",
    completed: "Completed",
    noTasksChecked: "No tasks checked",
    planStatusActive: "Active",
    planStatusTrialing: "Trial period",
    planStatusPastDue: "Payment required",
    planStatusCanceled: "Canceled",
    planStatusIncomplete: "Incomplete",
    planStatusUnpaid: "Unpaid",
    planStatusPaused: "Paused",
    moduleEdit: "Edit module",
    newModule: "New module",
    standard: "Standard",
    alreadyAdded: "Added",
    moduleAlreadyAdded: "This item has already been added",
    customModuleNameRequired: "Enter a name for the item.",
    noRestaurantLinked: "No restaurant is linked to your account.",
    customModuleSaveFailed: "Save failed: {message}",
    unexpectedError: "Unexpected error: {message}",
    unexpectedErrorRetry: "Unexpected error. Please try again.",
    moduleName: "Item name",
    moduleNamePlaceholder: "E.g. Soup core temperature",
    chooseIcon: "Choose an icon",
    moduleType: "Item type",
    moduleTypeNumber: "Number/Temperature",
    moduleTypeBoolean: "Yes/No",
    moduleTypeList: "List",
    customModuleHelp: "After creating it, you can add items in the management screen.",
    savingChanges: "Save changes",
    cancel: "Cancel",
    understood: "Got it",
    confirmEmail: "Confirm your email address",
    enterOtpCode: "Enter the 6-digit code from your email to continue.",
    oneTimeCode: "One-time code",
    enterSixDigitCode: "Enter the 6-digit code.",
    checking: "Checking…",
    checkCode: "Check code",
    latest30Days: "Last 30 days",
    generateNvwaReport: "Generate NVWA Report",
    noRegistrationsLast30Days: "No registrations in the last 30 days.",
    noRegistrationsFound: "No registrations found.",
    time: "Time",
    valueStatus: "Value/Status",
    remarks: "Remarks",
    details: "Details",
    overLimit: "Over limit",
    correctiveAction: "Corrective action",
    noRemarks: "No remarks.",
    photos: "Photos",
    photoAlt: "Photo {number} for registration",
    freeHistoryLimit: "The free version shows up to 30 days of history.",
    selectedReasons: "Selected reasons ({count})",
    unknownEquipment: "Unknown equipment",
    unknownItem: "Unknown item",
    unknown: "Unknown",
    unknownGroup: "Unknown group",
    noItemsChecked: "No items checked",
    unknownDate: "Unknown date",
    yesterday: "Yesterday",
    haccpLogbookTitle: "HACCP Logbook - SnelVink",
    reportUpgradeMessage:
      "Only available on the Basic plan. Upgrade to generate and print the NVWA report.",
    back: "Back",
    notSignedIn: "Not signed in. Please sign in again.",
    checkoutStartFailed: "Could not start Stripe Checkout.",
    portalOpenFailed: "Could not open Customer Portal.",
    paymentSuccess:
      "Payment successful - your subscription will update within a few seconds.",
    paymentCanceled: "Payment canceled. Your plan was not changed.",
    plans: "Plans",
    choosePlan: "Choose the plan that fits your kitchen.",
    currentPlan: "Current plan",
    currentPeriodEnds: "Current period runs until {date}.",
    opening: "Opening...",
    ownerOnlySubscription:
      "Only the owner can change the subscription. Ask your manager to upgrade.",
    invoicesStripe:
      "Invoices and payment methods are managed through Stripe. You can cancel your subscription at any time.",
    free: "Free",
    perMonth: "€ {price} / month",
    ownerOnly: "Owner only",
    upToStaff: "Up to {count} staff members",
    upgradeTo: "Upgrade to {plan}",
    planFreeTagline: "For one-person restaurants",
    planBasicTagline: "For an average business",
    planProTagline: "For large kitchens and chains",
    planFreeFeature1: "Owner only, no staff members",
    planFreeFeature2: "Basic HACCP registrations",
    planFreeFeature3: "History for the last 30 days",
    planFreeFeature4: "No photo attachments",
    planBasicFeature1: "Up to 10 staff members",
    planBasicFeature2: "Full HACCP history",
    planBasicFeature3: "Photo evidence for registrations",
    planBasicFeature4: "Generate NVWA PDF report",
    planProFeature1: "Up to 50 staff members",
    planProFeature2: "Everything in Basic",
    planProFeature3: "Priority support",
    planProFeature4: "Export to CSV (coming soon)",
    verifyEmailMissing: "No email address found on this account.",
    verifyEmailSendFailed:
      "Could not send an email. Check SMTP in Supabase or try again later.",
    verifyEmailSent:
      "Confirmation email sent. Open the link in your inbox to verify your email address.",
    retryError: "Something went wrong. Please try again.",
    emailNotVerified:
      "Email address not verified yet. Confirm your account to keep your data safe.",
    sending: "Sending...",
    verifyNow: "Verify now",
    itemOne: "Item 1",
    customModuleDefaultName: "Custom item",
    moduleNotFound: "Item not found.",
    moduleUnavailable:
      "This item no longer exists or is not available.",
    itemNotFound: "Item not found.",
    productNotFound: "Product not found.",
    equipmentNotFound: "Equipment not found.",
    locationNotFound: "Location not found.",
    fillName: "Enter a name.",
    addFailed: "Add failed.",
    deleteFailed: "Delete failed.",
    renameFailed: "Rename failed.",
    photoUploadFailed: "Photo upload failed. Please try again.",
    loadLocationsFailed: "Failed to load locations. Please try again.",
    loadProductsFailed: "Failed to load products. Please try again.",
    locationAddFailed: "Failed to add location.",
    productAddFailed: "Failed to add product.",
    equipmentAddFailed: "Failed to add equipment.",
    taskAddFailed: "Failed to add task.",
    standardTasksCreateFailed: "Failed to create default tasks.",
    confirmDeleteHistoryKept: 'Delete "{name}"? The history will be kept.',
    confirmDeleteLocation:
      'Delete "{name}"? All tasks in this location will also be deleted.',
    confirmDelete: 'Delete "{name}"?',
    editNamePrompt: "New name",
    editTaskNamePrompt: "New name for the task",
    editModuleTitle: "{module} - Edit",
    editProduct: "Edit product",
    editLocation: "Edit location",
    editItem: "Edit item",
    equipmentName: "Equipment name",
    productName: "Product name",
    locationName: "Location name",
    name: "Name",
    setDefaultValue: "Set default value",
    defaultValueStartsAt:
      "Every new registration starts at {value} {unit}.",
    defaultValueUsesLast:
      "Every new registration starts at the last saved measurement.",
    defaultValueUsesThis:
      "Every new registration starts at this default value.",
    defaultValueUsesLastMeasurement:
      "Every new registration starts at the last measurement.",
    defaultValue: "Default value",
    limitTemperature: "Temperature limit",
    limitTemperatureHelp:
      "Above this temperature, a corrective action must be entered.",
    limit: "Limit",
    limitValue: "Limit value",
    limitValueHelp:
      "Above this value, a corrective action must be entered.",
    range: "Range",
    rangeValueHelp:
      "Set a minimum and/or maximum. Outside this range, the value is treated as a deviation.",
    minimumValue: "Minimum",
    maximumValue: "Maximum",
    rangeInvalid: "Minimum value cannot be greater than maximum value.",
    requireCorrectionOnReject:
      "If rejected is selected: corrective action is required",
    requireCorrectionOutOfRange:
      "If value is outside range: corrective action is required",
    stepSize: "Step size",
    stepSizeHelp:
      "During registration, this is the increment size for the +/- buttons.",
    unit: "Unit",
    unitPlaceholder: "e.g. °C, kg, %",
    reasonsPerStatus: "Reasons per status",
    acceptReasonsTitle: "Reasons for approval",
    rejectReasonsTitle: "Reasons for rejection",
    acceptReasonsHelp:
      "Choose the possible reasons staff can select when approving.",
    rejectReasonsHelp:
      "Choose the possible reasons staff can select when rejecting.",
    defaultLabel: "Default",
    newReasonPlaceholder: "New reason...",
    addReason: "Add reason",
    other: "Other",
    describeOptional: "Describe (optional)",
    noReasonsConfigured: "No reasons configured for this product.",
    reasonSelected: "{count} reason selected",
    reasonsSelected: "{count} reasons selected",
    product: "Product",
    item: "Item",
    group: "Group",
    groups: "Groups",
    location: "Location",
    locations: "Locations",
    items: "Items",
    cleaningTasks: "Cleaning tasks",
    chooseLocation: "Choose a {name}",
    addLocation: "Add {name}",
    nameOfLocation: "{name} name",
    addProduct: "Add {name}",
    nameOfProduct: "{name} name",
    addTask: "Add task",
    taskNamePlaceholder: "Task name",
    addItem: "Add item",
    itemNamePlaceholder: "Item name",
    loadingLocations: "Loading locations...",
    loadingProducts: "Loading products...",
    loadingTasks: "Loading tasks...",
    loadingEquipment: "Loading equipment...",
    dateTimeLabel: "Date & time",
    receivedDateTimeLabel: "Date & time of receiving",
    measurementDateTimeLabel: "Date & time of measurement",
    rating: "Rating",
    completedCount: "{done}/{total} completed",
    noteOptional: "Remark (optional)",
    notePlaceholder: "Add a remark...",
    photosOptional: "Photos (optional)",
    maxPhotos: "Maximum {count} photos",
    addPhotoProgress: "Add photo ({current}/{max})",
    pickPhoto: "Take or choose photo (max {count})",
    removePhoto: "Remove photo {number}",
    selectAtLeastOneTask: "Check at least one task to save.",
    holdButtonHint:
      "Hold a button to adjust quickly. Tap the number to enter manually.",
    increaseOneDegreeFast:
      "Increase by one degree (hold for faster)",
    increaseTenthDegreeFast:
      "Increase by 0.1 degree (hold for faster)",
    decreaseOneDegreeFast:
      "Decrease by one degree (hold for faster)",
    decreaseTenthDegreeFast:
      "Decrease by 0.1 degree (hold for faster)",
    increaseStepFast:
      "Increase {step} {unit} (hold for faster)",
    decreaseStepFast:
      "Decrease {step} {unit} (hold for faster)",
    limitLabel: "Limit: {value} {unit}",
    valueOverLimit: "Value over limit ({value} {unit})",
    correctiveActionRequiredHelp:
      "Enter a corrective action to continue.",
    correctiveActionPlaceholder:
      "E.g. Set cooling to level 4, checked the door...",
    correctiveActionRequired:
      "Required: enter a corrective action.",
    loginTitle: "Sign in",
    registerTitle: "Register",
    emailAddress: "Email address",
    password: "Password",
    loginFailedCheck: "Sign in failed. Check your details.",
    loginFailedRetry: "Sign in failed. Please try again.",
    resendConfirmationFailed:
      "Could not send a new confirmation email. Please try again later.",
    unconfirmedEmailMessage:
      "Your email address has not been confirmed yet. Check your inbox and spam/promotions folder for the confirmation email to {email}.",
    resendConfirmation: "Resend confirmation email",
    sent: "Sent",
    newConfirmationSent:
      "New confirmation email sent. Do not forget to check your spam folder.",
    working: "Working...",
    accountType: "Account type",
    chooseAccountType: "Choose your account type",
    owner: "Owner",
    employee: "Staff",
    restaurantName: "Restaurant name",
    inviteCodeLabel: "Invite code",
    inviteCodePlaceholder: "E.g. 123456",
    inviteCodeHelp: "Ask your employer for this 6-digit code.",
    fillFullName: "Enter your name.",
    fillRestaurantName: "Enter the restaurant name.",
    invalidInviteCode: "Enter a valid 6-digit invite code.",
    staffLimitReached:
      "The restaurant has reached the maximum number of staff members. Ask your employer to upgrade the subscription.",
    inviteCodeInvalid:
      "The invite code is incorrect. Ask your employer for the correct 6-digit code.",
    registerFailed: "Registration failed.",
    registerFailedRetry: "Registration failed. Please try again.",
    createAccount: "Create account",
    noAccount: "No account yet?",
    alreadyHaveAccount: "Already have an account?",
    emailAlreadyRegistered:
      "This email address is already registered. Sign in or click 'Forgot password?' below.",
    confirmationMailSent:
      "We sent a confirmation email to {email}. Check your inbox and spam/promotions folder. Click the link to activate your account, then sign in.",
    scheduleAtLeastOneReminder: "Add at least one reminder.",
    scheduleReminderDateTime: "Enter a date and time for every reminder.",
    scheduleMinFrequency: "Choose a frequency of at least 1.",
    scheduleDailyTimes: "Enter a time for every daily registration.",
    scheduleWeeklyDays: "Choose {count} day(s) for this weekly task.",
    scheduleMonthlyDays: "Choose {count} day(s) for this monthly task.",
    scheduleYearlyDates: "Choose {count} date(s) for this yearly task.",
    manageItems: "Manage your items and settings",
    selectToRecord: "Select an item to record",
    lastValue: "Last value",
  },
} as const;

type TranslationKey = keyof (typeof translations)["nl"];

const termAliases: Record<string, TranslationKey> = {
  koeling: "koeling",
  cooling: "koeling",
  kerntemperatuur: "kerntemperatuur",
  "core temperature": "kerntemperatuur",
  schoonmaak: "schoonmaak",
  cleaning: "schoonmaak",
  ontvangst: "ontvangst",
  receiving: "ontvangst",
  goedgekeurd: "goedgekeurd",
  approved: "goedgekeurd",
  afgekeurd: "afgekeurd",
  rejected: "afgekeurd",
  anders: "other",
  other: "other",
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey, vars?: Record<string, string | number>) => string;
  translateHaccpText: (input: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      if (typeof window === "undefined") return "nl";
      const stored = window.localStorage.getItem(STORAGE_KEY);
      if (stored === "nl" || stored === "en") {
        return stored;
      }
    } catch {
      // ignore storage read failures
    }
    return "nl";
  });

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    try {
      window.localStorage.setItem(STORAGE_KEY, nextLanguage);
    } catch {
      // ignore storage write failures
    }
  };

  const value = useMemo<LanguageContextValue>(() => {
    const t = (key: TranslationKey, vars?: Record<string, string | number>) => {
      let template: string =
        translations[language][key] ?? translations.nl[key] ?? key;
      if (!vars) return template;
      Object.entries(vars).forEach(([varKey, varValue]) => {
        template = template.replace(`{${varKey}}`, String(varValue));
      });
      return template;
    };

    const translateHaccpText = (input: string) => {
      let output = input;
      Object.entries(termAliases).forEach(([alias, key]) => {
        const re = new RegExp(`\\b${alias}\\b`, "gi");
        output = output.replace(re, t(key));
      });
      return output;
    };

    return {
      language,
      setLanguage,
      t,
      translateHaccpText,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguageContext() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguageContext must be used inside LanguageProvider");
  }
  return ctx;
}
